### ISSUE TITLE
Google Chrome : page rendering issue

### ISSUE THREAD

**Issue by vaidls** [marcus67/little_brother#156]
FireFox is OK,  
Google Chrome  - STATUS  and ADMIN pages render with error. See  picture.

![Screenshot from 2021-10-09 16-56-11](https://user-images.githubusercontent.com/90566375/136663320-3f6e34b0-3ea3-4253-ae8f-083d4bfa466d.png)

**Comment by marcus67** [comment]
Thank you for reporting the error! Would it be possible to retrieve the log file and send it to me? I'm wondering if it contains a stack trace. Which revision did you use? Thanks a lot!

**Comment by vaidls** [comment]
Looks like this one : 

2021-10-12 19:53:34,244 - App - DEBUG - Best matching locale = fr
2021-10-12 19:53:34,245 - VersionChecker - INFO - Retrieving version information from RSS feed https://sourceforge.net/projects/little-brother/rss?path=/...
2021-10-12 19:53:35,339 - VersionChecker - DEBUG - Channel 'master' has latest version 0.4.9 with revision 108
2021-10-12 19:53:35,339 - VersionChecker - DEBUG - Channel 'release' has latest version 0.4.9 with revision 108
2021-10-12 19:53:35,476 - AdminViewHandler - ERROR - Exception 'expected '}' before end of string' while generating admin page
Traceback (most recent call last):
  File "/var/lib/little-brother/virtualenv/lib/python3.9/site-packages/little_brother/web/admin_view_handler.py", line 84, in admin_view
    page = flask.render_template(constants.ADMIN_HTML_TEMPLATE, **template_dict)
  File "/var/lib/little-brother/virtualenv/lib/python3.9/site-packages/flask/templating.py", line 147, in render_template
    return _render(
  File "/var/lib/little-brother/virtualenv/lib/python3.9/site-packages/flask/templating.py", line 128, in _render
    rv = template.render(context)
  File "/var/lib/little-brother/virtualenv/lib/python3.9/site-packages/jinja2/environment.py", line 1304, in render
    self.environment.handle_exception()
  File "/var/lib/little-brother/virtualenv/lib/python3.9/site-packages/jinja2/environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/var/lib/little-brother/virtualenv/lib/python3.9/site-packages/little_brother/templates/admin.template.html", line 96, in top-level template code
    <LI>{{ _(rule_template[0])|format(rule_template[1])|safe }}</LI>
  File "/var/lib/little-brother/virtualenv/lib/python3.9/site-packages/little_brother/web/web_server.py", line 207, in format
    return value.format(**param_dict)
  File "/var/lib/little-brother/virtualenv/lib/python3.9/site-packages/markupsafe/__init__.py", line 205, in format
    return self.__class__(formatter.vformat(self, args, kwargs))
  File "/usr/lib/python3.9/string.py", line 165, in vformat
    result, _ = self._vformat(format_string, args, kwargs, used_args, 2)
  File "/usr/lib/python3.9/string.py", line 174, in _vformat
    for literal_text, field_name, format_spec, conversion in \
ValueError: expected '}' before end of string
2021-10-12 19:53:36,230 - ApiViewHandler - DEBUG - Received 0 events from host 'pasakapc'
2021-10-12 19:53:36,230 - ApiViewHandler - DEBUG - Sending 0 events back to host 'pasakapc'
2021-10-12 19:53:36,291 - ApiViewHandler - DEBUG - Received 0 events from host 'fejapc'
2021-10-12 19:53:36,717 - ApiViewHandler - DEBUG - Sending 1 events back to host 'fejapc'
2021-10-12 19:53:37,114 - ApiViewHandler - DEBUG - Received status request for user 'feja'
2021-10-12 19:53:38,461 - ApiViewHandler - DEBUG - Received status request for user 'pasaka'
2021-10-12 19:53:38,858 - App - DEBUG - Woken by signal
2021-10-12 19:53:38,859 - App - DEBUG - Executing task app_control.check 0.006 [s] behind schedule... *** START ***
2021-10-12 19:53:38,859 - AppControl - DEBUG - Processing rules for all users START...
2021-10-12 19:53:38,878 - AppControl - DEBUG - StatInfo (user=teo, today:0[s], yesterday:518[s], ref-time:2021-10-12 19:53:38, previous Activity([2021-10-11 18:31:52, 2021-10-11 18:40:30], 0h08m38s, downtime=0h00m00s), current ---, secs-since-last-activity:25h13m08s)
2021-10-12 19:53:38,878 - AppControl - DEBUG - None

**Comment by marcus67** [comment]
Thanks for the log file! That was very helpful! The error was caused by a missing parenthesis in the French translation.
