### ISSUE TITLE
I'm unable to install on ubuntu and lubuntu

### ISSUE THREAD

**Issue by alkhachatryan** [marcus67/little_brother#205]
I cannot install it on both ubuntu and lubuntu and have exactly same error for 2 different machines with different distros:

 ```
 error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [28 lines of output]
      Traceback (most recent call last):
        File "/var/lib/little-brother/virtualenv/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/var/lib/little-brother/virtualenv/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/var/lib/little-brother/virtualenv/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-xpm5t0x6/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 332, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=[])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-xpm5t0x6/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 302, in _get_build_requires
          self.run_setup()
        File "/tmp/pip-build-env-xpm5t0x6/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 516, in run_setup
          super().run_setup(setup_script=setup_script)
        File "/tmp/pip-build-env-xpm5t0x6/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 318, in run_setup
          exec(code, locals())
        File "<string>", line 6, in <module>
        File "/usr/lib/python3.12/inspect.py", line 1278, in getsource
          lines, lnum = getsourcelines(object)
                        ^^^^^^^^^^^^^^^^^^^^^^
        File "/usr/lib/python3.12/inspect.py", line 1260, in getsourcelines
          lines, lnum = findsource(object)
                        ^^^^^^^^^^^^^^^^^^
        File "/usr/lib/python3.12/inspect.py", line 1089, in findsource
          raise OSError('could not get source code')
      OSError: could not get source code
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

```

My machines are both intel cpu. No idea what to do. Docker is not a solution since lubuntu (which is for my kid) is a laptop a little bit powerful than calculator :D

**Comment by marcus67** [comment]
Hi @alkhachatryan: Thank you for your bug report. I will try to look into this soon.

**Comment by alkhachatryan** [comment]
Thanks. Looking forward for a response, since I think this is a briliant project.

P.S. while you find a solution, I keep in mind the following commands :D 

```
#ssh into kid's laptop, then:
sudo pkill -u KID_USERNAME #killall and logout
sudo usermod -L KID_USERNAME # lock kid user
sudo usermod -U KID_USERNAME #unlock kid user
```

**Comment by marcus67** [comment]
Hi @alkhachatryan, I finally found the problem with the installation. It was a downstream dependency in the package `playsound` which had not been maintained in a long while and has become incompatible with the current setup process. I switched to `playsound3` and and seems to work now.

**Comment by alkhachatryan** [comment]
@marcus67 will try it and be back here
